from flask import Flask, request, jsonify
import yt_dlp
import os
import errno
import sys
import re

app = Flask(__name__)

def strip_ansi(text):
    ansi_escape = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')
    return ansi_escape.sub('', text)

@app.route('/extract', methods=['GET'])
def extract_url():
    video_url = request.args.get('url')
    if not video_url:
        return jsonify({'error': 'Missing url parameter'}), 400

    try:
        ydl_opts = {
            'format': 'best', # You can change this to 'bestaudio/best' if you want audio only
            'quiet': True,
            'no_warnings': True,
        }

        # Use paths relative to the application file
        base_dir = os.path.dirname(os.path.abspath(__file__))
        temp_cookie_file = os.path.join(base_dir, 'temp_netscape_cookies.txt')
        
        # Hardcoded cookies (Raw string)
        cookie_content = "YSC=mPN2RlQOeJI; VISITOR_INFO1_LIVE=i5HKL2Q2sK4; VISITOR_PRIVACY_METADATA=CgJJThIEGgAgVA%3D%3D; __Secure-YNID=14.YT=ko7PoSDxV7hDh08uhnsqhVA7wKNECXch8HqlpS2GDDTgj0MkGQeqXfAGt0sZC83quZQaf-yGsuU2Iuu7k-iGMIkKaP17TI1oeTCO-yASy7qy8papmniEi5Oke2hk8WZdM05yREOg0Oiaq6DTmMIjx_Bc96xiIyWLBKpBqRjmP2UMEcx0B5lxUU9dRjK-ehUJH2uRdKHLF3tBMcY0i_0hpfWeMzwamPLIK4sro9snK-kN2X_rV8l1dqpaLeXZ63ESUt8vyJhP-796hbqV1rLduW34-ELp5Fwenwln5z23nTmDyCx28sUqYmktbkAeTH4Kr_HAO3MdLLXlos5Nbpe_tA; __Secure-ROLLOUT_TOKEN=CNaz5b2Njazi-wEQ2aG5_rXfkQMY8oGY_7XfkQM%3D; PREF=f4=4000000&f6=40000000&tz=Asia.Calcutta&f7=100; GPS=1; CONSISTENCY=APeVyi_VmY4OEsvAwXm3EcgFN-wEMJ38XEgnuQBG3yfWwswCiHaMwII7SBwFyWBBxWG5n-YojsQ81BOnYfVduA"

        # Convert raw cookie string to Netscape format
        print("Using hardcoded cookies. Converting to Netscape format...")
        
        # Check for missing auth cookies
        if 'SID=' not in cookie_content and '__Secure-1PSID=' not in cookie_content:
            print("WARNING: Cookies seem to lack login information (SID/__Secure-1PSID). YouTube might still block you.")

        with open(temp_cookie_file, 'w') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file is generated by the app.\n\n")
            
            # Split by semicolon, handle potential newlines
            cookies = [c.strip() for c in cookie_content.replace('\n', '').split(';') if c.strip()]
            
            for cookie in cookies:
                if '=' in cookie:
                    name, value = cookie.split('=', 1)
                    # Write for both .youtube.com and www.youtube.com to be safe
                    f.write(f".youtube.com\tTRUE\t/\tTRUE\t2147483647\t{name}\t{value}\n")
                    f.write(f"www.youtube.com\tTRUE\t/\tTRUE\t2147483647\t{name}\t{value}\n")
        
        ydl_opts['cookies'] = temp_cookie_file
        print(f"Using converted cookies from: {temp_cookie_file}")
        
        # Add client spoofing to bypass bot detection
        ydl_opts['extractor_args'] = {
            'youtube': {
                'player_client': ['android', 'web'],
                'player_skip': ['configs', 'js'],
                'zerorating': ['1']
            }
        }

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(video_url, download=False)
            
            # Handle playlists (return first video or handle as needed)
            if 'entries' in info:
                info = info['entries'][0]

            download_url = info.get('url')
            title = info.get('title')
            thumbnail = info.get('thumbnail')
            duration = info.get('duration')

            return jsonify({
                'title': title,
                'download_url': download_url,
                'thumbnail': thumbnail,
                'duration': duration
            })

    except Exception as e:
        error_message = strip_ansi(str(e))
        return jsonify({'error': error_message}), 500


if __name__ == '__main__':
    # Allow overriding the port via environment variable `PORT`.
    # Default is 5000 to preserve previous behavior.
    port = int(os.environ.get('PORT', '5001'))

    # FLASK_DEBUG env var can be used to control debug mode (1=true, 0=false)
    debug_env = os.environ.get('FLASK_DEBUG')
    if debug_env is None:
        debug = True
    else:
        debug = str(debug_env).lower() not in ('0', 'false', 'no')

    try:
        app.run(debug=debug, host='0.0.0.0', port=port)
    except OSError as e:
        if getattr(e, 'errno', None) == errno.EADDRINUSE:
            print(f"Port {port} is already in use.\n"
                  f"- To run on a different port: `export PORT=5001 && python app.py`\n"
                  f"- To find the process using the port: `lsof -nP -iTCP:{port} -sTCP:LISTEN`\n"
                  f"- To stop it: `kill <PID>` (or `kill -9 <PID>` if needed).`")
            sys.exit(1)
        raise
